/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorJuez;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Juez;
import ec.edu.ups.modelo.Persona;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class VentanaRegistros extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJueces
     */
    
    ControladorJuez controladorJuez;
    ControladorPersona controladorPersona;
    
    public VentanaRegistros(ControladorJuez controladorJuez, ControladorPersona controladorPersona) {
        initComponents();
        this.controladorJuez = controladorJuez;
        this.controladorPersona = controladorPersona;
        
    }
    
    public void cargarDatosPersonas() {
        DefaultTableModel modelo = (DefaultTableModel) jTableJueces.getModel();
        modelo.setRowCount(0);
        
        for (Persona p : controladorPersona.getListado()) {
            Object[] rowData = {p.getNombre(), p.getApellido(), p.getCedula(), p.getDireccion(), p.getGenero(), p.getEstadoCivil()};
            modelo.addRow(rowData);
        }
        jTableJueces.setModel(modelo);
    }
    
    public void cargarDatosJueces() {
        DefaultTableModel modelo = (DefaultTableModel) jTableJueces.getModel();
        modelo.setRowCount(0);
        
        for (Juez juez : controladorJuez.getListado()) {
            Object[] rowData = {juez.getNombre(), juez.getApellido(), juez.getCedula(), juez.getDireccion(), juez.getGenero(), juez.getEstadoCivil()};
            modelo.addRow(rowData);
        }
        jTableJueces.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJueces = new javax.swing.JTable();
        jButtonJueces = new javax.swing.JButton();
        jButtonPersonaRegistradas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabelTitulo.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registros");

        jTableJueces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Direccion", "Genero", "Estado civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableJueces);

        jButtonJueces.setText("Mostrar jueces disponibles ");
        jButtonJueces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJuecesActionPerformed(evt);
            }
        });

        jButtonPersonaRegistradas.setText("Mostrar Personas registradas");
        jButtonPersonaRegistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonaRegistradasActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar Matrimonios Registrados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonJueces)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonPersonaRegistradas)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJueces)
                    .addComponent(jButtonPersonaRegistradas)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJuecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJuecesActionPerformed
        // TODO add your handling code here:
        cargarDatosJueces();
    }//GEN-LAST:event_jButtonJuecesActionPerformed

    private void jButtonPersonaRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonaRegistradasActionPerformed
        // TODO add your handling code here:
        cargarDatosPersonas();
    }//GEN-LAST:event_jButtonPersonaRegistradasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonJueces;
    private javax.swing.JButton jButtonPersonaRegistradas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableContactos;
    private javax.swing.JTable jTableJueces;
    // End of variables declaration//GEN-END:variables
}
