/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Persona;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class VentanaPersonasRegistradas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPersonasRegistradas
     */
    
    private ControladorPersona controladorPersona;
    private JTextField nombre;
    private JTextField cedula;
    
    public VentanaPersonasRegistradas(ControladorPersona controladorPersona, JTextField nombre, JTextField cedula) {
        initComponents();
        this.controladorPersona = controladorPersona;
        this.nombre = nombre;
        this.cedula = cedula;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public Persona getPersonaSeleccionada() {
        int filaIndex = jTablePersonas.getSelectedRow();
        Persona persona = controladorPersona.buscar(new Persona(jTablePersonas.getValueAt(filaIndex, 2).toString()));
        return persona;
    }
    
    public void limpiar() {
        jTextFieldNombre1.setText("");
        jTextFieldApellido1.setText("");
        jTextFieldDireccion1.setText("");
        jTextFieldCedula1.setText("");
    }
    
    public void cargarDatosPersonas() {
        DefaultTableModel modelo = (DefaultTableModel) jTablePersonas.getModel();
        modelo.setRowCount(0);
        
        for (Persona p : controladorPersona.getListado()) {
            Object[] rowData = {p.getNombre(), p.getApellido(), p.getCedula(), p.getDireccion(), p.getGenero(), p.getEstadoCivil()};
            modelo.addRow(rowData);
        }
        jTablePersonas.setModel(modelo);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabelCedula1 = new javax.swing.JLabel();
        jLabeDireccion1 = new javax.swing.JLabel();
        jLabelGenero1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldCedula1 = new javax.swing.JTextField();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jSpinnerGenero = new javax.swing.JSpinner();
        jLabelFechaNacimiento1 = new javax.swing.JLabel();
        jSpinnerfechaNacimiento = new javax.swing.JSpinner();
        jLabelEstadoCivil1 = new javax.swing.JLabel();
        jSpinnerEstadoCivil = new javax.swing.JSpinner();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        jCancelar = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabelNombre1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNombre1.setText("Nombre: ");

        jLabelApellido1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelApellido1.setText("Apellido:");

        jTextFieldNombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelCedula1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCedula1.setText("Cedula:");

        jLabeDireccion1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabeDireccion1.setText("Direccion:");

        jLabelGenero1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelGenero1.setText("Genero:");

        jTextFieldApellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldCedula1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldDireccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSpinnerGenero.setModel(new javax.swing.SpinnerListModel(new String[] {"Masculino", "Femenino"}));

        jLabelFechaNacimiento1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelFechaNacimiento1.setText("Fecha de Nacimiento:");

        jSpinnerfechaNacimiento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1606513080000L), null, null, java.util.Calendar.ERA));

        jLabelEstadoCivil1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelEstadoCivil1.setText("Estado civil: ");

        jSpinnerEstadoCivil.setModel(new javax.swing.SpinnerListModel(new String[] {"Soltero", "Casado", "Divorsiado"}));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Direccion", "Genero", "Estado civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePersonas);

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jCancelar)
                        .addGap(116, 116, 116)
                        .addComponent(jButtonGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCedula1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelFechaNacimiento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelGenero1)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelApellido1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabeDireccion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelEstadoCivil1)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonLimpiar))
                                    .addComponent(jSpinnerEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula1)
                    .addComponent(jTextFieldCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeDireccion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoCivil1)
                    .addComponent(jSpinnerEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacimiento1)
                    .addComponent(jSpinnerfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jLabelGenero1)
                    .addComponent(jSpinnerGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldCedula1.getText().trim().equals("") || jTextFieldNombre1.getText().trim().equals("") || jTextFieldApellido1.getText().trim().equals("")
            || jTextFieldDireccion1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor rellene todos los campos");

        } else {
            Persona p = new Persona(controladorPersona.generarId(), jTextFieldNombre1.getText(), jTextFieldApellido1.getText()
                , jTextFieldCedula1.getText(), jTextFieldDireccion1.getText(), jSpinnerGenero.getValue().toString(), LocalDate.MIN, jSpinnerEstadoCivil.getValue().toString());

            if (controladorPersona.crear(p)) {
                JOptionPane.showMessageDialog(this, "agregado con exito");
                limpiar();
                cargarDatosPersonas();

            } else {
                JOptionPane.showMessageDialog(this, "No se guardaron los datos porfavor vuelva a intentarlo");

            }

        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jTablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Persona persona = getPersonaSeleccionada();
        nombre.setText(persona.getNombre() + " " + persona.getApellido());
        cedula.setText(persona.getCedula());
        
    }//GEN-LAST:event_jTablePersonasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jLabeDireccion1;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCedula1;
    private javax.swing.JLabel jLabelEstadoCivil1;
    private javax.swing.JLabel jLabelFechaNacimiento1;
    private javax.swing.JLabel jLabelGenero1;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerEstadoCivil;
    private javax.swing.JSpinner jSpinnerGenero;
    private javax.swing.JSpinner jSpinnerfechaNacimiento;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldCedula1;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldNombre1;
    // End of variables declaration//GEN-END:variables
}
