/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorMatrimonio;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Juez;
import ec.edu.ups.modelo.Matrimonio;
import ec.edu.ups.modelo.Persona;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ariel
 */
public class VentanaMatrimonios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMatrimonios
     */
    
    private Juez juez;
    private ControladorPersona controladorPersona;
    private ControladorMatrimonio controladorMatrimonio;
    
    public VentanaMatrimonios(ControladorPersona controladorPersona, Juez juez, ControladorMatrimonio controladorMatrimonio) {
        initComponents();
        this.controladorPersona = controladorPersona;
        this.juez = juez;
    }

    public JTextField getjTextFieldJuez() {
        return jTextFieldJuez;
    }

    public JTextField getjTextFieldFecha() {
        return jTextFieldFecha;
    }
    
    public void limpiar() {
        jTextFieldCedulaContrayente1.setText("");
        jTextFieldCedulaContrayente2.setText("");
        jTextFieldCedulaTestigo1.setText("");
        jTextFieldCedulaTestigo2.setText("");
        jTextFieldContrayente1.setText("");
        jTextFieldContrayente2.setText("");
        jTextFieldFecha.setText(LocalDate.now().toString());
        jTextFieldLugar.setText("");
        jTextFieldTestigo1.setText("");
        jTextFieldTestigo2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelContrayentes = new javax.swing.JLabel();
        jLabelTestigos = new javax.swing.JLabel();
        jTextFieldCedulaContrayente1 = new javax.swing.JTextField();
        jTextFieldContrayente1 = new javax.swing.JTextField();
        jTextFieldTestigo1 = new javax.swing.JTextField();
        jTextFieldCedulaTestigo1 = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jLabelJuez = new javax.swing.JLabel();
        jTextFieldJuez = new javax.swing.JTextField();
        jLabelFecha1 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelContrayentes1 = new javax.swing.JLabel();
        jLabelContrayentes2 = new javax.swing.JLabel();
        jTextFieldContrayente2 = new javax.swing.JTextField();
        jLabelContrayentes3 = new javax.swing.JLabel();
        jTextFieldCedulaContrayente2 = new javax.swing.JTextField();
        jLabelContrayentes4 = new javax.swing.JLabel();
        jLabelTestigos1 = new javax.swing.JLabel();
        jTextFieldTestigo2 = new javax.swing.JTextField();
        jLabelContrayentes5 = new javax.swing.JLabel();
        jTextFieldCedulaTestigo2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabelTitulo.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Nuevo Matrimonio");

        jLabelContrayentes.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes.setText("Cedula:");

        jLabelTestigos.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelTestigos.setText("Primer Testigo:");

        jTextFieldCedulaContrayente1.setEditable(false);

        jTextFieldContrayente1.setEditable(false);

        jTextFieldTestigo1.setEditable(false);

        jTextFieldCedulaTestigo1.setEditable(false);

        jLabelFecha.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelFecha.setText("Fecha: ");

        jLabelJuez.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelJuez.setText("Juez: ");

        jTextFieldJuez.setEditable(false);

        jLabelFecha1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelFecha1.setText("Lugar de Celebracion:");

        jTextFieldFecha.setEditable(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Seleccionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Seleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabelContrayentes1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes1.setText("Primer Contrayente:");

        jLabelContrayentes2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes2.setText("Segundo Contrayente:");

        jTextFieldContrayente2.setEditable(false);

        jLabelContrayentes3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes3.setText("Cedula:");

        jTextFieldCedulaContrayente2.setEditable(false);

        jLabelContrayentes4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes4.setText("Cedula:");

        jLabelTestigos1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelTestigos1.setText("Primer Testigo:");

        jTextFieldTestigo2.setEditable(false);

        jLabelContrayentes5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabelContrayentes5.setText("Cedula:");

        jTextFieldCedulaTestigo2.setEditable(false);

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jLabelJuez))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJuez, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCancelar)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButtonGuardar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelFecha1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelContrayentes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCedulaContrayente1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelContrayentes1)
                                    .addComponent(jLabelContrayentes2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldContrayente1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabelTestigos)
                                        .addGap(122, 122, 122))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTestigos1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelContrayentes4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldCedulaTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jTextFieldTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jButton3)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelContrayentes3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCedulaContrayente2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldContrayente2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton4)
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelContrayentes5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCedulaTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTitulo)
                                .addGap(127, 127, 127))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTestigos)
                    .addComponent(jLabelContrayentes1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContrayente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jTextFieldTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContrayentes)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCedulaContrayente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCedulaTestigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelContrayentes4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrayentes2)
                    .addComponent(jLabelTestigos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContrayente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jTextFieldTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrayentes3)
                    .addComponent(jTextFieldCedulaContrayente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrayentes5)
                    .addComponent(jTextFieldCedulaTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFecha1)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJuez)
                    .addComponent(jTextFieldJuez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButton5)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaPersonasRegistradas ventanaPersonasRegistradas = new VentanaPersonasRegistradas(controladorPersona, jTextFieldContrayente1, jTextFieldCedulaContrayente1);
        ventanaPersonasRegistradas.setVisible(true);
        ventanaPersonasRegistradas.cargarDatosPersonas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaPersonasRegistradas ventanaPersonasRegistradas = new VentanaPersonasRegistradas(controladorPersona, jTextFieldContrayente2, jTextFieldCedulaContrayente2);
        ventanaPersonasRegistradas.setVisible(true);
        ventanaPersonasRegistradas.cargarDatosPersonas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VentanaPersonasRegistradas ventanaPersonasRegistradas = new VentanaPersonasRegistradas(controladorPersona, jTextFieldTestigo1, jTextFieldCedulaTestigo1);
        ventanaPersonasRegistradas.setVisible(true);
        ventanaPersonasRegistradas.cargarDatosPersonas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        VentanaPersonasRegistradas ventanaPersonasRegistradas = new VentanaPersonasRegistradas(controladorPersona, jTextFieldTestigo2, jTextFieldCedulaTestigo2);
        ventanaPersonasRegistradas.setVisible(true);
        ventanaPersonasRegistradas.cargarDatosPersonas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldCedulaContrayente1.getText().trim().equals("") || jTextFieldCedulaContrayente2.getText().trim().equals("") || jTextFieldCedulaTestigo1.getText().trim().equals("")
            || jTextFieldTestigo2.getText().trim().equals("") || jTextFieldLugar.getText().trim().equals("") ) {
            JOptionPane.showMessageDialog(this, "Porfavor rellene todos los campos");

        } else {
            Persona c1 = new Persona(jTextFieldCedulaContrayente1.getText());
            c1.setEstadoCivil("casado");
            c1 = controladorPersona.buscar(c1);
            System.out.println(c1.toString());
            Persona c2 = new Persona(jTextFieldCedulaContrayente2.getText());
            c2 = controladorPersona.buscar(c2);
            c2.setEstadoCivil("casado");
            System.out.println(c2.toString());
            Persona t1 = new Persona(jTextFieldCedulaTestigo1.getText());
            c1 = controladorPersona.buscar(c1);
            System.out.println(t1.toString());
            Persona t2 = new Persona(jTextFieldCedulaTestigo2.getText());
            t2 = controladorPersona.buscar(t2);
            System.out.println(t2.toString());
            
            Matrimonio matrimonio = new Matrimonio(controladorMatrimonio.generarId(), LocalDate.now(), jTextFieldLugar.getText(), c1, c2, t1, t2,juez);
            
            if (controladorMatrimonio.crear(matrimonio)) {
                JOptionPane.showMessageDialog(this, "Matrimonio guardado con exito");
                controladorPersona.actualizar(c1);
                controladorPersona.actualizar(c2);
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "No se guardaron los datos porfavor vuelva a intentarlo");

            }

        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContrayentes;
    private javax.swing.JLabel jLabelContrayentes1;
    private javax.swing.JLabel jLabelContrayentes2;
    private javax.swing.JLabel jLabelContrayentes3;
    private javax.swing.JLabel jLabelContrayentes4;
    private javax.swing.JLabel jLabelContrayentes5;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelJuez;
    private javax.swing.JLabel jLabelTestigos;
    private javax.swing.JLabel jLabelTestigos1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCedulaContrayente1;
    private javax.swing.JTextField jTextFieldCedulaContrayente2;
    private javax.swing.JTextField jTextFieldCedulaTestigo1;
    private javax.swing.JTextField jTextFieldCedulaTestigo2;
    private javax.swing.JTextField jTextFieldContrayente1;
    private javax.swing.JTextField jTextFieldContrayente2;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldJuez;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldTestigo1;
    private javax.swing.JTextField jTextFieldTestigo2;
    // End of variables declaration//GEN-END:variables
}
